import type { InfusionDrug } from "./calc";

/**
 * Catálogo de infusões contínuas com diluições padronizadas de UTI/emergência.
 * Concentrações já normalizadas em mcg/mL (ou U/mL).
 */
export const infusionDrugs: InfusionDrug[] = [
  /* ---------------- Vasoativas ---------------- */
  {
    id: "noradrenalina",
    name: "Noradrenalina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.01,
    max: 3.3,
    step: 0.01,
    usualMin: 0.05,
    usualMax: 1,
    start: 0.37,
    dilutions: [
      {
        label: "40 mcg/mL",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "4 mL (1 amp) + 96 mL SG 5% EV [1 mL = 40 mcg]",
        concentration: 40,
        concUnit: "mcg/mL",
      },
      {
        label: "64 mcg/mL",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "16 mL (4 amp) + 234 mL SG 5% EV [1 mL = 64 mcg]",
        concentration: 64,
        concUnit: "mcg/mL",
      },
      {
        label: "80 mcg/mL",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "8 mL (2 amp) + 92 mL SG 5% EV [1 mL = 80 mcg]",
        concentration: 80,
        concUnit: "mcg/mL",
      },
      {
        label: "128 mcg/mL",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "32 mL (8 amp) + 218 mL SG 5% EV [1 mL = 128 mcg]",
        concentration: 128,
        concUnit: "mcg/mL",
      },
      {
        label: "200 mcg/mL",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "20 mL (5 amp) + 80 mL SG 5% EV [1 mL = 200 mcg]",
        concentration: 200,
        concUnit: "mcg/mL",
      },
      {
        label: "400 mcg/mL",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "40 mL (10 amp) + 60 mL SG 5% EV [1 mL = 400 mcg]",
        concentration: 400,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Preferir acesso venoso central; em periférico, vigiar extravasamento.",
      "Meta habitual de PAM ≥ 65 mmHg, individualizada.",
    ],
  },
  {
    id: "adrenalina",
    name: "Adrenalina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.1,
    max: 2,
    step: 0.01,
    usualMin: 0.1,
    usualMax: 1,
    start: 0.1,
    dilutions: [
      {
        label: "20 mcg/mL",
        presentation: "Adrenalina 1 mg/mL",
        recipe: "5 mL (5 amp) + 245 mL SF 0,9% EV [1 mL = 20 mcg]",
        concentration: 20,
        concUnit: "mcg/mL",
      },
      {
        label: "60 mcg/mL",
        presentation: "Adrenalina 1 mg/mL",
        recipe: "15 mL (15 amp) + 235 mL SF 0,9% EV [1 mL = 60 mcg]",
        concentration: 60,
        concUnit: "mcg/mL",
      },
      {
        label: "100 mcg/mL",
        presentation: "Adrenalina 1 mg/mL",
        recipe: "10 mL (10 amp) + 90 mL SF 0,9% EV [1 mL = 100 mcg]",
        concentration: 100,
        concUnit: "mcg/mL",
      },
      {
        label: "200 mcg/mL",
        presentation: "Adrenalina 1 mg/mL",
        recipe: "20 mL (20 amp) + 80 mL SF 0,9% EV [1 mL = 200 mcg]",
        concentration: 200,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Monitorar taquiarritmias, isquemia e lactato (efeito β2)."],
  },
  {
    id: "vasopressina",
    name: "Vasopressina",
    category: "vasoativas",
    doseUnit: "U/min",
    min: 0.01,
    max: 0.04,
    step: 0.005,
    usualMin: 0.01,
    usualMax: 0.04,
    start: 0.025,
    dilutions: [
      {
        label: "0,2 UI/mL",
        presentation: "Vasopressina 20 UI/mL",
        recipe: "1 mL (20 UI) + 99 mL SG 5% EV [1 mL = 0,2 UI]",
        concentration: 0.2,
        concUnit: "U/mL",
      },
      {
        label: "0,4 UI/mL",
        presentation: "Vasopressina 20 UI/mL",
        recipe: "2 mL (40 UI) + 98 mL SG 5% EV [1 mL = 0,4 UI]",
        concentration: 0.4,
        concUnit: "U/mL",
      },
      {
        label: "1 UI/mL",
        presentation: "Vasopressina 20 UI/mL",
        recipe: "5 mL (100 UI) + 95 mL SG 5% EV [1 mL = 1 UI]",
        concentration: 1,
        concUnit: "U/mL",
      },
    ],
    notes: ["Dose fixa, não titulada por peso. Poupador de catecolamina no choque séptico."],
  },
  {
    id: "dobutamina",
    name: "Dobutamina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 2,
    max: 20,
    step: 0.5,
    usualMin: 2,
    usualMax: 20,
    start: 11,
    dilutions: [
      {
        label: "1.000 mcg/mL",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "20 mL (1 amp) + 230 mL SG 5% EV [1 mL = 1 mg]",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
      {
        label: "2.000 mcg/mL",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "40 mL (2 amp) + 210 mL SG 5% EV [1 mL = 2 mg]",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
      {
        label: "3.000 mcg/mL",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "60 mL (3 amp) + 190 mL SF 0,9% EV [1 mL = 3 mg]",
        concentration: 3000,
        concUnit: "mcg/mL",
      },
      {
        label: "4.000 mcg/mL",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "80 mL (4 amp) + 170 mL SG 5% EV [1 mL = 4 mg]",
        concentration: 4000,
        concUnit: "mcg/mL",
      },
      {
        label: "5.000 mcg/mL",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "80 mL (4 amp) + 120 mL SG 5% EV [1 mL = 5 mg]",
        concentration: 5000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Inotrópico: pode reduzir PA por vasodilatação. Vigiar taquicardia."],
  },
  {
    id: "milrinona",
    name: "Milrinona",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.125,
    max: 0.75,
    step: 0.005,
    usualMin: 0.375,
    usualMax: 0.75,
    start: 0.56,
    dilutions: [
      {
        label: "100 mcg/mL",
        presentation: "Milrinona 1 mg/mL",
        recipe: "10 mL (10 mg) + 90 mL SG 5% EV [1 mL = 100 mcg]",
        concentration: 100,
        concUnit: "mcg/mL",
      },
      {
        label: "200 mcg/mL",
        presentation: "Milrinona 1 mg/mL",
        recipe: "20 mL (20 mg) + 80 mL SG 5% EV [1 mL = 200 mcg]",
        concentration: 200,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Inodilatador: hipotensão é o efeito adverso limitante.",
      "Excreção renal — reduzir dose na disfunção renal.",
    ],
  },
  {
    id: "levosimendana",
    name: "Levosimendana",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.05,
    max: 0.2,
    step: 0.01,
    usualMin: 0.05,
    usualMax: 0.2,
    start: 0.13,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Levosimendana 2,5 mg/mL",
        recipe: "5 mL + 495 mL SG 5% EV, BI [1 mL = 25 mcg]",
        concentration: 25,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Infusão habitual de 24 h; efeito hemodinâmico persiste por dias.",
      "Vigiar hipotensão e hipocalemia.",
    ],
  },
  {
    id: "dopamina",
    name: "Dopamina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 1,
    max: 50,
    step: 0.5,
    usualMin: 5,
    usualMax: 15,
    start: 10,
    dilutions: [
      {
        label: "1.000 mcg/mL",
        presentation: "Dopamina 50 mg/10 mL",
        recipe: "50 mL (5 amp) + 200 mL SF 0,9% EV [1 mL = 1 mg]",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
      {
        label: "2.000 mcg/mL",
        presentation: "Dopamina 50 mg/10 mL",
        recipe: "100 mL (10 amp) + 150 mL SF 0,9% EV [1 mL = 2 mg]",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
      {
        label: "4.000 mcg/mL",
        presentation: "Dopamina 50 mg/10 mL",
        recipe: "200 mL (20 amp) + 50 mL SF 0,9% EV [1 mL = 4 mg]",
        concentration: 4000,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Faixas: dopa 1–5, beta 5–15 e alfa 15–50 mcg/kg/min.",
      "Maior risco de arritmia que a noradrenalina — não é 1ª escolha no choque.",
    ],
  },
  {
    id: "nitroglicerina",
    name: "Nitroglicerina",
    category: "vasoativas",
    doseUnit: "mcg/min",
    min: 5,
    max: 100,
    step: 1,
    usualMin: 5,
    usualMax: 100,
    start: 53,
    dilutions: [
      {
        label: "100 mcg/mL",
        presentation: "Nitroglicerina 5 mg/mL",
        recipe: "5 mL (25 mg) + 245 mL SF 0,9% EV [1 mL = 100 mcg]",
        concentration: 100,
        concUnit: "mcg/mL",
      },
      {
        label: "200 mcg/mL",
        presentation: "Nitroglicerina 5 mg/mL",
        recipe: "10 mL (50 mg) + 240 mL SF 0,9% EV [1 mL = 200 mcg]",
        concentration: 200,
        concUnit: "mcg/mL",
      },
      {
        label: "400 mcg/mL",
        presentation: "Nitroglicerina 5 mg/mL",
        recipe: "20 mL (100 mg) + 230 mL SF 0,9% EV [1 mL = 400 mcg]",
        concentration: 400,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Contraindicada com inibidores de PDE-5 e no IAM de VD."],
  },
  {
    id: "nitroprussiato",
    name: "Nitroprussiato de sódio",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.1,
    max: 10,
    step: 0.05,
    usualMin: 0.3,
    usualMax: 4,
    start: 5.05,
    dilutions: [
      {
        label: "100 mcg/mL",
        presentation: "Nitroprussiato 50 mg/2 mL",
        recipe: "2 mL (1 amp) + 498 mL SG 5% EV [1 mL = 100 mcg]",
        concentration: 100,
        concUnit: "mcg/mL",
      },
      {
        label: "200 mcg/mL",
        presentation: "Nitroprussiato 50 mg/2 mL",
        recipe: "2 mL (1 amp) + 248 mL SG 5% EV [1 mL = 200 mcg]",
        concentration: 200,
        concUnit: "mcg/mL",
      },
      {
        label: "500 mcg/mL",
        presentation: "Nitroprussiato 50 mg/2 mL",
        recipe: "4 mL (2 amp) + 196 mL SG 5% EV [1 mL = 500 mcg]",
        concentration: 500,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Proteger da luz. Risco de intoxicação por cianeto em uso prolongado ou dose alta."],
  },


  /* ---------------- Sedação e analgesia ---------------- */
  {
    id: "fentanil",
    name: "Fentanil",
    category: "sedacao",
    doseUnit: "mcg/kg/h",
    min: 0.3,
    max: 3,
    step: 0.05,
    usualMin: 0.3,
    usualMax: 3,
    start: 1,
    dilutions: [
      {
        label: "25 mcg/mL",
        presentation: "Fentanil 50 mcg/mL",
        recipe: "50 mL + 50 mL SF 0,9% EV [1 mL = 25 mcg]",
        concentration: 25,
        concUnit: "mcg/mL",
      },
      {
        label: "10 mcg/mL",
        presentation: "Fentanil 50 mcg/mL",
        recipe: "20 mL (1.000 mcg) + 80 mL SF 0,9% EV [1 mL = 10 mcg]",
        concentration: 10,
        concUnit: "mcg/mL",
      },
      {
        label: "50 mcg/mL (puro)",
        presentation: "Fentanil 50 mcg/mL",
        recipe: "Frasco puro em bomba de seringa [1 mL = 50 mcg]",
        concentration: 50,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Tolerância e íleo em uso prolongado. Analgesia antes de aprofundar sedação."],
  },
  {
    id: "midazolam",
    name: "Midazolam",
    category: "sedacao",
    doseUnit: "mcg/kg/min",
    min: 0.25,
    max: 5,
    step: 0.05,
    usualMin: 0.25,
    usualMax: 5,
    start: 1,
    dilutions: [
      {
        label: "1 mg/mL",
        presentation: "Midazolam 5 mg/mL",
        recipe: "20 mL (100 mg) + 80 mL SF 0,9% EV [1 mL = 1 mg]",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
      {
        label: "0,5 mg/mL",
        presentation: "Midazolam 5 mg/mL",
        recipe: "20 mL (100 mg) + 180 mL SF 0,9% EV [1 mL = 500 mcg]",
        concentration: 500,
        concUnit: "mcg/mL",
      },
      {
        label: "2 mg/mL",
        presentation: "Midazolam 5 mg/mL",
        recipe: "40 mL (200 mg) + 60 mL SF 0,9% EV [1 mL = 2 mg]",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
      {
        label: "5 mg/mL (puro)",
        presentation: "Midazolam 5 mg/mL",
        recipe: "Frasco puro em bomba de seringa [1 mL = 5 mg]",
        concentration: 5000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Acúmulo em disfunção renal/hepática. Avaliar despertar diário."],
  },
  {
    id: "cetamina-inf",
    name: "Cetamina (infusão)",
    category: "sedacao",
    doseUnit: "mg/kg/h",
    min: 0.1,
    max: 2,
    step: 0.05,
    usualMin: 0.5,
    usualMax: 1,
    start: 0.5,
    dilutions: [
      {
        label: "2 mg/mL",
        presentation: "Cetamina 50 mg/mL",
        recipe: "10 mL (500 mg) + 240 mL SF 0,9% EV [1 mL = 2 mg]",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
      {
        label: "1 mg/mL",
        presentation: "Cetamina 50 mg/mL",
        recipe: "10 mL (500 mg) + 490 mL SF 0,9% EV [1 mL = 1 mg]",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
      {
        label: "5 mg/mL",
        presentation: "Cetamina 50 mg/mL",
        recipe: "10 mL (500 mg) + 90 mL SF 0,9% EV [1 mL = 5 mg]",
        concentration: 5000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Útil como poupador de opioide e no broncoespasmo."],
  },
  {
    id: "dexmedetomidina",
    name: "Dexmedetomidina",
    category: "sedacao",
    doseUnit: "mcg/kg/h",
    min: 0.2,
    max: 1.5,
    step: 0.05,
    usualMin: 0.2,
    usualMax: 1.5,
    start: 0.4,
    dilutions: [
      {
        label: "4 mcg/mL",
        presentation: "Dexmedetomidina 100 mcg/mL",
        recipe: "2 mL (200 mcg) + 48 mL SF 0,9% EV [1 mL = 4 mcg]",
        concentration: 4,
        concUnit: "mcg/mL",
      },
      {
        label: "8 mcg/mL",
        presentation: "Dexmedetomidina 100 mcg/mL",
        recipe: "4 mL (400 mcg) + 46 mL SF 0,9% EV [1 mL = 8 mcg]",
        concentration: 8,
        concUnit: "mcg/mL",
      },
      {
        label: "2 mcg/mL",
        presentation: "Dexmedetomidina 100 mcg/mL",
        recipe: "2 mL (200 mcg) + 98 mL SF 0,9% EV [1 mL = 2 mcg]",
        concentration: 2,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Bradicardia e hipotensão. Não produz sedação profunda isoladamente."],
  },
  {
    id: "propofol",
    name: "Propofol",
    category: "sedacao",
    doseUnit: "mg/kg/h",
    min: 0.5,
    max: 5,
    step: 0.1,
    usualMin: 0.5,
    usualMax: 4,
    start: 1.5,
    dilutions: [
      {
        label: "1% (10 mg/mL)",
        presentation: "Propofol 10 mg/mL",
        recipe: "Frasco puro em bomba de seringa/infusora [1 mL = 10 mg]",
        concentration: 10000,
        concUnit: "mcg/mL",
      },
      {
        label: "2% (20 mg/mL)",
        presentation: "Propofol 20 mg/mL",
        recipe: "Frasco puro em bomba de seringa/infusora [1 mL = 20 mg]",
        concentration: 20000,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Acima de 4 mg/kg/h por > 48 h: risco de síndrome da infusão do propofol.",
      "Considerar o aporte calórico lipídico na prescrição nutricional.",
    ],
  },

  /* ---------------- Bloqueio neuromuscular ---------------- */
  {
    id: "rocuronio",
    name: "Rocurônio (infusão)",
    category: "bloqueio",
    doseUnit: "mcg/kg/min",
    min: 2,
    max: 15,
    step: 0.5,
    usualMin: 4,
    usualMax: 12,
    start: 6,
    dilutions: [
      {
        label: "5 mg/mL",
        presentation: "Rocurônio 10 mg/mL (5 mL)",
        recipe: "500 mg (50 mL) + 50 mL SF 0,9% EV [1 mL = 5 mg]",
        concentration: 5000,
        concUnit: "mcg/mL",
      },
      {
        label: "2 mg/mL",
        presentation: "Rocurônio 10 mg/mL (5 mL)",
        recipe: "200 mg (20 mL) + 80 mL SF 0,9% EV [1 mL = 2 mg]",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
      {
        label: "10 mg/mL (puro)",
        presentation: "Rocurônio 10 mg/mL (5 mL)",
        recipe: "Frasco puro em bomba de seringa [1 mL = 10 mg]",
        concentration: 10000,
        concUnit: "mcg/mL",
      },
    ],
    bolus: { label: "Bolus de intubação", perKg: 1.2, unit: "mg" },
    notes: ["Bloqueio exige sedação e analgesia plenas. Monitorar TOF quando disponível."],
  },
  {
    id: "cisatracurio",
    name: "Cisatracúrio",
    category: "bloqueio",
    doseUnit: "mcg/kg/min",
    min: 0.5,
    max: 10,
    step: 0.5,
    usualMin: 1,
    usualMax: 3,
    start: 1.5,
    dilutions: [
      {
        label: "1 mg/mL",
        presentation: "Cisatracúrio 2 mg/mL (10 mL)",
        recipe: "100 mg (50 mL) + 50 mL SF 0,9% EV [1 mL = 1 mg]",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
      {
        label: "0,4 mg/mL",
        presentation: "Cisatracúrio 2 mg/mL (10 mL)",
        recipe: "40 mg (20 mL) + 80 mL SF 0,9% EV [1 mL = 400 mcg]",
        concentration: 400,
        concUnit: "mcg/mL",
      },
      {
        label: "2 mg/mL (puro)",
        presentation: "Cisatracúrio 2 mg/mL (10 mL)",
        recipe: "Frasco puro em bomba de seringa [1 mL = 2 mg]",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
    ],
    bolus: { label: "Bolus inicial", perKg: 0.15, unit: "mg" },
    notes: ["Eliminação de Hofmann — preferido em disfunção renal/hepática."],
  },


  /* ---------------- Outras infusões ---------------- */
  {
    id: "insulina-ev",
    name: "Insulina regular EV",
    category: "outras",
    doseUnit: "U/h",
    min: 0.5,
    max: 20,
    step: 0.5,
    usualMin: 1,
    usualMax: 10,
    start: 2,
    dilutions: [
      {
        label: "1 UI/mL",
        presentation: "Insulina regular 100 UI/mL",
        recipe: "50 UI (0,5 mL) + 50 mL SF 0,9% EV (desprezar 10 mL do equipo)",
        concentration: 1,
        concUnit: "U/mL",
      },
    ],
    notes: [
      "Glicemia capilar de hora em hora até estabilizar.",
      "Repor potássio se K < 5,2 mEq/L; suspender insulina se K < 3,3.",
    ],
  },
  {
    id: "heparina-inf",
    name: "Heparina não fracionada",
    category: "outras",
    doseUnit: "U/kg/h",
    min: 2,
    max: 25,
    step: 1,
    usualMin: 12,
    usualMax: 18,
    start: 18,
    dilutions: [
      {
        label: "100 UI/mL",
        presentation: "Heparina 5.000 UI/mL",
        recipe: "25.000 UI (5 mL) + 245 mL SF 0,9% EV",
        concentration: 100,
        concUnit: "U/mL",
      },
      {
        label: "50 UI/mL",
        presentation: "Heparina 5.000 UI/mL",
        recipe: "25.000 UI (5 mL) + 495 mL SF 0,9% EV",
        concentration: 50,
        concUnit: "U/mL",
      },
    ],
    bolus: { label: "Bolus inicial", perKg: 80, unit: "U", max: 10000 },
    notes: [
      "TTPa em 6 h do início e a cada ajuste; alvo 1,5–2,5x o controle.",
      "Síndrome coronariana: bolus 60 UI/kg (máx 4.000) e 12 UI/kg/h (máx 1.000/h).",
    ],
  },
  {
    id: "amiodarona",
    name: "Amiodarona",
    category: "outras",
    doseUnit: "mg/h",
    min: 15,
    max: 60,
    step: 5,
    usualMin: 30,
    usualMax: 60,
    start: 60,
    dilutions: [
      {
        label: "1.800 mcg/mL",
        presentation: "Amiodarona 50 mg/mL (3 mL)",
        recipe: "900 mg (18 mL) + 482 mL SG 5% EV [1 mL = 1,8 mg]",
        concentration: 1800,
        concUnit: "mcg/mL",
      },
      {
        label: "3.600 mcg/mL",
        presentation: "Amiodarona 50 mg/mL (3 mL)",
        recipe: "900 mg (18 mL) + 232 mL SG 5% EV [1 mL = 3,6 mg]",
        concentration: 3600,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Esquema clássico: 1 mg/min por 6 h, depois 0,5 mg/min por 18 h."],
  },
];
