import type { InfusionDrug } from "./calc";

/**
 * Catálogo de infusões contínuas com diluições padronizadas de UTI/emergência.
 * Concentrações já normalizadas em mcg/mL (ou U/mL).
 */
export const infusionDrugs: InfusionDrug[] = [
  /* ---------------- Vasoativas ---------------- */
  {
    id: "noradrenalina",
    name: "Noradrenalina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.01,
    max: 3.3,
    step: 0.01,
    usualMin: 0.05,
    usualMax: 1,
    start: 0.1,
    dilutions: [
      {
        label: "Simples",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "4 mL (1 amp) + 96 mL SG 5% EV",
        concentration: 40,
        concUnit: "mcg/mL",
      },
      {
        label: "Concentrada",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "20 mL (5 amp) + 80 mL SG 5% EV",
        concentration: 200,
        concUnit: "mcg/mL",
      },
      {
        label: "Dupla concentração",
        presentation: "Noradrenalina 4 mg/4 mL",
        recipe: "40 mL (10 amp) + 60 mL SG 5% EV",
        concentration: 400,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Preferir acesso venoso central; em periférico, vigiar extravasamento.",
      "Meta habitual de PAM ≥ 65 mmHg, individualizada.",
    ],
  },
  {
    id: "adrenalina",
    name: "Adrenalina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.01,
    max: 2,
    step: 0.01,
    usualMin: 0.05,
    usualMax: 0.5,
    start: 0.1,
    dilutions: [
      {
        label: "Simples",
        presentation: "Adrenalina 1 mg/mL",
        recipe: "10 mL (10 amp) + 90 mL SF 0,9% EV",
        concentration: 100,
        concUnit: "mcg/mL",
      },
      {
        label: "Concentrada",
        presentation: "Adrenalina 1 mg/mL",
        recipe: "20 mL (20 amp) + 80 mL SF 0,9% EV",
        concentration: 200,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Monitorar taquiarritmias, isquemia e lactato (efeito β2)."],
  },
  {
    id: "vasopressina",
    name: "Vasopressina",
    category: "vasoativas",
    doseUnit: "U/min",
    min: 0.005,
    max: 0.06,
    step: 0.005,
    usualMin: 0.01,
    usualMax: 0.04,
    start: 0.03,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Vasopressina 20 UI/mL",
        recipe: "1 mL (20 UI) + 99 mL SF 0,9% EV",
        concentration: 0.2,
        concUnit: "U/mL",
      },
    ],
    notes: ["Dose fixa, não titulada por peso. Poupador de catecolamina no choque séptico."],
  },
  {
    id: "dobutamina",
    name: "Dobutamina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 1,
    max: 20,
    step: 0.5,
    usualMin: 2.5,
    usualMax: 15,
    start: 5,
    dilutions: [
      {
        label: "Simples",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "20 mL (1 amp) + 230 mL SG 5% EV",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
      {
        label: "Concentrada",
        presentation: "Dobutamina 250 mg/20 mL",
        recipe: "40 mL (2 amp) + 210 mL SG 5% EV",
        concentration: 2000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Inotrópico: pode reduzir PA por vasodilatação. Vigiar taquicardia."],
  },
  {
    id: "dopamina",
    name: "Dopamina",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 1,
    max: 20,
    step: 0.5,
    usualMin: 5,
    usualMax: 15,
    start: 5,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Dopamina 50 mg/10 mL",
        recipe: "50 mL (5 amp) + 200 mL SG 5% EV",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Maior risco de arritmia que a noradrenalina — não é 1ª escolha no choque."],
  },
  {
    id: "nitroglicerina",
    name: "Nitroglicerina",
    category: "vasoativas",
    doseUnit: "mcg/min",
    min: 5,
    max: 200,
    step: 5,
    usualMin: 10,
    usualMax: 100,
    start: 10,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Nitroglicerina 25 mg/5 mL",
        recipe: "5 mL (1 amp) + 245 mL SG 5% EV",
        concentration: 100,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Contraindicada com inibidores de PDE-5 e no IAM de VD."],
  },
  {
    id: "nitroprussiato",
    name: "Nitroprussiato de sódio",
    category: "vasoativas",
    doseUnit: "mcg/kg/min",
    min: 0.1,
    max: 10,
    step: 0.1,
    usualMin: 0.3,
    usualMax: 4,
    start: 0.5,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Nitroprussiato 50 mg/2 mL",
        recipe: "2 mL (1 amp) + 248 mL SG 5% EV",
        concentration: 200,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Proteger da luz. Risco de intoxicação por cianeto em uso prolongado ou dose alta."],
  },

  /* ---------------- Sedação e analgesia ---------------- */
  {
    id: "midazolam",
    name: "Midazolam",
    category: "sedacao",
    doseUnit: "mg/kg/h",
    min: 0.01,
    max: 0.3,
    step: 0.01,
    usualMin: 0.02,
    usualMax: 0.1,
    start: 0.05,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Midazolam 5 mg/mL (10 mL)",
        recipe: "100 mg (20 mL) + 80 mL SF 0,9% EV",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Acúmulo em disfunção renal/hepática. Avaliar despertar diário."],
  },
  {
    id: "propofol",
    name: "Propofol",
    category: "sedacao",
    doseUnit: "mcg/kg/min",
    min: 5,
    max: 80,
    step: 1,
    usualMin: 10,
    usualMax: 50,
    start: 20,
    dilutions: [
      {
        label: "Puro 1%",
        presentation: "Propofol 10 mg/mL",
        recipe: "Frasco puro em bomba de seringa/infusora",
        concentration: 10000,
        concUnit: "mcg/mL",
      },
      {
        label: "Puro 2%",
        presentation: "Propofol 20 mg/mL",
        recipe: "Frasco puro em bomba de seringa/infusora",
        concentration: 20000,
        concUnit: "mcg/mL",
      },
    ],
    notes: [
      "Acima de 4 mg/kg/h por > 48 h: risco de síndrome da infusão do propofol.",
      "Considerar o aporte calórico lipídico na prescrição nutricional.",
    ],
  },
  {
    id: "fentanil",
    name: "Fentanil",
    category: "sedacao",
    doseUnit: "mcg/kg/h",
    min: 0.5,
    max: 10,
    step: 0.5,
    usualMin: 0.7,
    usualMax: 5,
    start: 1,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Fentanil 50 mcg/mL (10 mL)",
        recipe: "1.000 mcg (20 mL) + 80 mL SF 0,9% EV",
        concentration: 10,
        concUnit: "mcg/mL",
      },
      {
        label: "Concentrada",
        presentation: "Fentanil 50 mcg/mL (10 mL)",
        recipe: "2.500 mcg (50 mL) + 50 mL SF 0,9% EV",
        concentration: 25,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Tolerância e íleo em uso prolongado. Analgesia antes de aprofundar sedação."],
  },
  {
    id: "dexmedetomidina",
    name: "Dexmedetomidina",
    category: "sedacao",
    doseUnit: "mcg/kg/h",
    min: 0.2,
    max: 1.4,
    step: 0.1,
    usualMin: 0.2,
    usualMax: 1.2,
    start: 0.4,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Dexmedetomidina 100 mcg/mL (2 mL)",
        recipe: "200 mcg (2 mL) + 48 mL SF 0,9% EV",
        concentration: 4,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Bradicardia e hipotensão. Não produz sedação profunda isoladamente."],
  },
  {
    id: "cetamina-inf",
    name: "Cetamina (infusão)",
    category: "sedacao",
    doseUnit: "mg/kg/h",
    min: 0.05,
    max: 2,
    step: 0.05,
    usualMin: 0.1,
    usualMax: 1,
    start: 0.3,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Cetamina 50 mg/mL (10 mL)",
        recipe: "500 mg (10 mL) + 90 mL SF 0,9% EV",
        concentration: 5000,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Útil como poupador de opioide e no broncoespasmo."],
  },

  /* ---------------- Bloqueio neuromuscular ---------------- */
  {
    id: "rocuronio",
    name: "Rocurônio (infusão)",
    category: "bloqueio",
    doseUnit: "mcg/kg/min",
    min: 2,
    max: 15,
    step: 0.5,
    usualMin: 4,
    usualMax: 12,
    start: 6,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Rocurônio 10 mg/mL (5 mL)",
        recipe: "500 mg (50 mL) + 50 mL SF 0,9% EV",
        concentration: 5000,
        concUnit: "mcg/mL",
      },
    ],
    bolus: { label: "Bolus de intubação", perKg: 1.2, unit: "mg" },
    notes: ["Bloqueio exige sedação e analgesia plenas. Monitorar TOF quando disponível."],
  },
  {
    id: "cisatracurio",
    name: "Cisatracúrio",
    category: "bloqueio",
    doseUnit: "mcg/kg/min",
    min: 0.5,
    max: 10,
    step: 0.5,
    usualMin: 1,
    usualMax: 3,
    start: 1.5,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Cisatracúrio 2 mg/mL (10 mL)",
        recipe: "100 mg (50 mL) + 50 mL SF 0,9% EV",
        concentration: 1000,
        concUnit: "mcg/mL",
      },
    ],
    bolus: { label: "Bolus inicial", perKg: 0.15, unit: "mg" },
    notes: ["Eliminação de Hofmann — preferido em disfunção renal/hepática."],
  },

  /* ---------------- Outras infusões ---------------- */
  {
    id: "insulina-ev",
    name: "Insulina regular EV",
    category: "outras",
    doseUnit: "U/h",
    min: 0.5,
    max: 20,
    step: 0.5,
    usualMin: 1,
    usualMax: 10,
    start: 2,
    dilutions: [
      {
        label: "1 UI/mL",
        presentation: "Insulina regular 100 UI/mL",
        recipe: "50 UI (0,5 mL) + 50 mL SF 0,9% EV (desprezar 10 mL do equipo)",
        concentration: 1,
        concUnit: "U/mL",
      },
    ],
    notes: [
      "Glicemia capilar de hora em hora até estabilizar.",
      "Repor potássio se K < 5,2 mEq/L; suspender insulina se K < 3,3.",
    ],
  },
  {
    id: "heparina-inf",
    name: "Heparina não fracionada",
    category: "outras",
    doseUnit: "U/kg/h",
    min: 2,
    max: 25,
    step: 1,
    usualMin: 12,
    usualMax: 18,
    start: 18,
    dilutions: [
      {
        label: "100 UI/mL",
        presentation: "Heparina 5.000 UI/mL",
        recipe: "25.000 UI (5 mL) + 245 mL SF 0,9% EV",
        concentration: 100,
        concUnit: "U/mL",
      },
      {
        label: "50 UI/mL",
        presentation: "Heparina 5.000 UI/mL",
        recipe: "25.000 UI (5 mL) + 495 mL SF 0,9% EV",
        concentration: 50,
        concUnit: "U/mL",
      },
    ],
    bolus: { label: "Bolus inicial", perKg: 80, unit: "U", max: 10000 },
    notes: [
      "TTPa em 6 h do início e a cada ajuste; alvo 1,5–2,5x o controle.",
      "Síndrome coronariana: bolus 60 UI/kg (máx 4.000) e 12 UI/kg/h (máx 1.000/h).",
    ],
  },
  {
    id: "amiodarona",
    name: "Amiodarona",
    category: "outras",
    doseUnit: "mg/h",
    min: 15,
    max: 60,
    step: 5,
    usualMin: 30,
    usualMax: 60,
    start: 60,
    dilutions: [
      {
        label: "Padrão",
        presentation: "Amiodarona 50 mg/mL (3 mL)",
        recipe: "900 mg (18 mL) + 482 mL SG 5% EV",
        concentration: 1800,
        concUnit: "mcg/mL",
      },
    ],
    notes: ["Esquema clássico: 1 mg/min por 6 h, depois 0,5 mg/min por 18 h."],
  },
];
